"""Arts of War, Treachery, and Command card data.

Auto-generated by scripts/build_cards.py from
reference/Inferno_Arts_of_War_Reference.txt (event/capability names,
event_kind hint) and Inferno Playbook p.64 (War-event flags).

Per BRIEF: per-card EFFECTS are Phase 4 deferred. Phase 2 needs only
IDs, names, side, is_war (for CtA trigger), and event_kind (for the
3.1.3 draw flow).
"""

from __future__ import annotations

GUELPH_CARDS = [
    {
        "id": "F1",
        "side": "guelph",
        "event_name": "Ambush",
        "capability_name": "Stores & Well Water",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F2",
        "side": "guelph",
        "event_name": "Betrayals",
        "capability_name": "Guastatori",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F3",
        "side": "guelph",
        "event_name": "Surprise",
        "capability_name": "Siege Towers",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F4",
        "side": "guelph",
        "event_name": "Sudden Clash",
        "capability_name": "Trebuchets",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F5",
        "side": "guelph",
        "event_name": "Road Works",
        "capability_name": "War Engineers",
        "is_war": False,
        "event_kind": "this_campaign"
    },
    {
        "id": "F6",
        "side": "guelph",
        "event_name": "Hills",
        "capability_name": "Hills",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F7",
        "side": "guelph",
        "event_name": "Greek Fire",
        "capability_name": "Greek Fire",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F8",
        "side": "guelph",
        "event_name": "Swamp",
        "capability_name": "Balestre Grosse",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F9",
        "side": "guelph",
        "event_name": "Genova breaks Pisan blockade",
        "capability_name": "Genova breaks Pisan blockade",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F10",
        "side": "guelph",
        "event_name": "Closed Gates",
        "capability_name": "Closed Gates",
        "is_war": False,
        "event_kind": "this_campaign"
    },
    {
        "id": "F11",
        "side": "guelph",
        "event_name": "Poggio Bonizio answers Firenze's call",
        "capability_name": "Poggio Bonizio answers Firenze's call",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F12",
        "side": "guelph",
        "event_name": "Camp Attack",
        "capability_name": "Army Reserve",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F13",
        "side": "guelph",
        "event_name": "No Time for Cowards",
        "capability_name": "No Time for Cowards",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F14",
        "side": "guelph",
        "event_name": "Provenzano sent as ambassador",
        "capability_name": "Provenzano sent as ambassador",
        "is_war": False,
        "event_kind": "this_campaign"
    },
    {
        "id": "F15",
        "side": "guelph",
        "event_name": "Casole",
        "capability_name": "Casole",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F16",
        "side": "guelph",
        "event_name": "A Bloody Red Stream",
        "capability_name": "A Bloody Red Stream",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F17",
        "side": "guelph",
        "event_name": "Foreign Help",
        "capability_name": "Foreign Help",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F18",
        "side": "guelph",
        "event_name": "Grosseto",
        "capability_name": "La Cavallata",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F19",
        "side": "guelph",
        "event_name": "Volterra",
        "capability_name": "Gualdana",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F20",
        "side": "guelph",
        "event_name": "Heat & Frost",
        "capability_name": "Masnadieri",
        "is_war": False,
        "event_kind": "this_levy"
    },
    {
        "id": "F21",
        "side": "guelph",
        "event_name": "Primo Popolo",
        "capability_name": "Distringitores",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F22",
        "side": "guelph",
        "event_name": "Manfredi holds back",
        "capability_name": "Tau Company",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "F23",
        "side": "guelph",
        "event_name": "Treasurers",
        "capability_name": "Via Francigena",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F24",
        "side": "guelph",
        "event_name": "Doctors",
        "capability_name": "Astrologers",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "F25",
        "side": "guelph",
        "event_name": "Val d'Orcia",
        "capability_name": "Reinforced Walls",
        "is_war": True,
        "event_kind": "immediate"
    },
    {
        "id": "F26",
        "side": "guelph",
        "event_name": "Montalcino",
        "capability_name": "Costruttori",
        "is_war": True,
        "event_kind": "immediate"
    }
]

GHIBELLINE_CARDS = [
    {
        "id": "S1",
        "side": "ghibelline",
        "event_name": "Ambush",
        "capability_name": "Stores & Well Water",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S2",
        "side": "ghibelline",
        "event_name": "Betrayals",
        "capability_name": "Guastatori",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S3",
        "side": "ghibelline",
        "event_name": "Surprise",
        "capability_name": "Siege Towers",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S4",
        "side": "ghibelline",
        "event_name": "Sudden Clash",
        "capability_name": "Trebuchets",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S5",
        "side": "ghibelline",
        "event_name": "Road Works",
        "capability_name": "War Engineers",
        "is_war": False,
        "event_kind": "this_campaign"
    },
    {
        "id": "S6",
        "side": "ghibelline",
        "event_name": "Feditori",
        "capability_name": "Feditori",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S7",
        "side": "ghibelline",
        "event_name": "Greek Fire",
        "capability_name": "Luceria",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S8",
        "side": "ghibelline",
        "event_name": "Swamp",
        "capability_name": "Balestre Grosse",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S9",
        "side": "ghibelline",
        "event_name": "Pope at Bay flees to Viterbo",
        "capability_name": "Pope at Bay flees to Viterbo",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S10",
        "side": "ghibelline",
        "event_name": "A Better Paid Death",
        "capability_name": "A Better Paid Death",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S11",
        "side": "ghibelline",
        "event_name": "Volterra",
        "capability_name": "Volterra",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S12",
        "side": "ghibelline",
        "event_name": "Camp Attack",
        "capability_name": "Army Reserve",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S13",
        "side": "ghibelline",
        "event_name": "Gentle Usilia ransoms prisoners",
        "capability_name": "Gentle Usilia",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S14",
        "side": "ghibelline",
        "event_name": "Friars sent to deceive Florentines",
        "capability_name": "Friars",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S15",
        "side": "ghibelline",
        "event_name": "War Loans",
        "capability_name": "War Loans",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S16",
        "side": "ghibelline",
        "event_name": "Bocca degli Abati",
        "capability_name": "Bocca degli Abati",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S17",
        "side": "ghibelline",
        "event_name": "Ghibelline Refugees",
        "capability_name": "Ghibelline Refugees",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S18",
        "side": "ghibelline",
        "event_name": "Cortona",
        "capability_name": "La Cavallata",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S19",
        "side": "ghibelline",
        "event_name": "Brigands",
        "capability_name": "Gualdana",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S20",
        "side": "ghibelline",
        "event_name": "Heat & Frost",
        "capability_name": "Masnadieri",
        "is_war": False,
        "event_kind": "this_levy"
    },
    {
        "id": "S21",
        "side": "ghibelline",
        "event_name": "Constituto",
        "capability_name": "Sovrintendente",
        "is_war": False,
        "event_kind": "this_campaign"
    },
    {
        "id": "S22",
        "side": "ghibelline",
        "event_name": "Closed Gates",
        "capability_name": "Manfredi",
        "is_war": False,
        "event_kind": "this_campaign"
    },
    {
        "id": "S23",
        "side": "ghibelline",
        "event_name": "Economic Sanctions",
        "capability_name": "Taglia",
        "is_war": False,
        "event_kind": "immediate"
    },
    {
        "id": "S24",
        "side": "ghibelline",
        "event_name": "Doctors",
        "capability_name": "Astrologers",
        "is_war": False,
        "event_kind": "hold"
    },
    {
        "id": "S25",
        "side": "ghibelline",
        "event_name": "Maremma",
        "capability_name": "Reinforced Walls",
        "is_war": True,
        "event_kind": "immediate"
    },
    {
        "id": "S26",
        "side": "ghibelline",
        "event_name": "Montepulciano",
        "capability_name": "Costruttori",
        "is_war": True,
        "event_kind": "immediate"
    }
]

AOW_CARDS_BY_ID = {c["id"]: c for c in GUELPH_CARDS + GHIBELLINE_CARDS}

TREACHERY_LORD_IDS = ['pisa', 'astimberg', 'santa_fiora', 'giordano', 'siena', 'provenzano', 'orvieto', 'guido_guerra', 'arezzo', 'firenze', 'colle', 'lucca']
# Treachery card ids — per 1.4.3, one Treachery Command card per Lord.
TREACHERY_CARDS = {
    "treachery_pisa": {"lord_id": "pisa", "kind": "treachery"},
    "treachery_astimberg": {"lord_id": "astimberg", "kind": "treachery"},
    "treachery_santa_fiora": {"lord_id": "santa_fiora", "kind": "treachery"},
    "treachery_giordano": {"lord_id": "giordano", "kind": "treachery"},
    "treachery_siena": {"lord_id": "siena", "kind": "treachery"},
    "treachery_provenzano": {"lord_id": "provenzano", "kind": "treachery"},
    "treachery_orvieto": {"lord_id": "orvieto", "kind": "treachery"},
    "treachery_guido_guerra": {"lord_id": "guido_guerra", "kind": "treachery"},
    "treachery_arezzo": {"lord_id": "arezzo", "kind": "treachery"},
    "treachery_firenze": {"lord_id": "firenze", "kind": "treachery"},
    "treachery_colle": {"lord_id": "colle", "kind": "treachery"},
    "treachery_lucca": {"lord_id": "lucca", "kind": "treachery"},
}

# Command cards — one per non-Comune Lord, command rating on the
# Lord mat in static_data.
COMMAND_CARDS = {
    "command_pisa": {"lord_id": "pisa", "kind": "command"},
    "command_astimberg": {"lord_id": "astimberg", "kind": "command"},
    "command_santa_fiora": {"lord_id": "santa_fiora", "kind": "command"},
    "command_giordano": {"lord_id": "giordano", "kind": "command"},
    "command_siena": {"lord_id": "siena", "kind": "command"},
    "command_provenzano": {"lord_id": "provenzano", "kind": "command"},
    "command_orvieto": {"lord_id": "orvieto", "kind": "command"},
    "command_guido_guerra": {"lord_id": "guido_guerra", "kind": "command"},
    "command_arezzo": {"lord_id": "arezzo", "kind": "command"},
    "command_firenze": {"lord_id": "firenze", "kind": "command"},
    "command_colle": {"lord_id": "colle", "kind": "command"},
    "command_lucca": {"lord_id": "lucca", "kind": "command"},
}

# Convenience: card sides by id
CARDS_BY_SIDE = {
    "guelph":     [c["id"] for c in GUELPH_CARDS],
    "ghibelline": [c["id"] for c in GHIBELLINE_CARDS],
}

# War-event flag (for CtA trigger detection — 3.5)
WAR_EVENT_IDS = {c["id"] for c in GUELPH_CARDS + GHIBELLINE_CARDS if c["is_war"]}

# Pass cards (per 4.1.1: fill Plan when a side has too few on-map Lords).
# Modeled as a single virtual ID; each side may include any number of these
# in its Plan, capped by Plan size for that Season.
PASS_CARD_ID = "PASS"
